#include "Arduino.h"
#include <stdio.h>

// Include the itch header file
#include <itch.h>

// Include the header of the code files generated by glitch
#include <out.h>

// Place functions that itch will call on action events into
// 	a code and header file that get included by itch
// For this example: my_funcs.h and my_funcs.cpp

// No need to include it here unless its also used for main loop work
// #include <my_funcs.h>

// Globally declare an itch singleton
// Note: It's possible to use it as a local, though since it is designed
// 	to be inserted between your program code and all "console" / Serial
//  communications it is likely to be instantiated regularly. On resource
//  constrained devices this means a hit to the stack when ever it comes
//  into scope (particularly the input buffer). Better to declare it global
//  so that it is allocated in .bss (if on Arduino) and its buffer usage
//  is visible at build time.
ITCH itch;

void setup() {
	// Call Begin() passing the HardwareSerial to use, and the speed
	itch.Begin(Serial, 9600);
}

void loop() {
	// Do some work

	// Call Poll() in the loop
	itch.Poll();
}


